// examples/vue2/src/App.vue
<template>
  <div id="app">
    <div class="left-menu">
      <menu-list :items="items" />
    </div>
    <div class="right-body">
      <router-view></router-view>
    </div>
    <el-button class="clean-1" type="primary" @click="showBaseInfo">
      查看核心基础信息
    </el-button>
    <div>
      <el-button class="clean-2" type="danger" @click="cleanTracingList">
        清除所有事件信息
      </el-button>
    </div>
  </div>
</template>

<script>
import { dynamicRouterMap } from './router/router.dynamic'
import axios from 'axios'

// 视频资源地址
// https://blog.csdn.net/qq_17497931/article/details/80824328

export default {
  data() {
    return {
      items: [],
      baseInfo: {}
    }
  },
  created() {
    this.items = dynamicRouterMap.filter(item => item.path !== '/')
  },
  methods: {
    cleanTracingList() {
      axios.post('/cleanTracingList').then(() => {
        this.$message.success('清除成功')
      })
    },
    handleOpen(key, keyPath) {
      console.log(key, keyPath)
    },
    handleClose(key, keyPath) {
      console.log(key, keyPath)
    },
    getBaseInfo() {
      return axios.get('/getBaseInfo').then(res => {
        this.baseInfo = res.data.data
      })
    },
    showBaseInfo() {
      this.getBaseInfo().finally(() => {
        if (this.baseInfo) {
          const displayInfo = Object.keys(this.baseInfo).reduce((pre, key) => {
            const value = JSON.stringify(this.baseInfo[key])
            pre += `<div class='pop-line'><div>${key}: </div><span>${value}</span></div>`
            return pre
          }, '')
          this.$alert(displayInfo, '核心基础信息', {
            dangerouslyUseHTMLString: true,
            showConfirmButton: false,
            closeOnClickModal: true,
            callback: () => {
              // action
            }
          })
        }
      })
    }
  }
}
</script>

<style scoped lang="scss">
#app {
  display: flex;
  .left-menu {
    width: 260px;
  }
  .right-body {
    flex: 1;
    height: 100vh;
    overflow-y: auto;
    padding: 20px;
  }
  .clean-1 {
    position: fixed;
    bottom: 80px;
    left: 20px;
    width: 220px;
    height: 40px;
  }
  .clean-2 {
    position: fixed;
    bottom: 20px;
    left: 20px;
    width: 220px;
    height: 40px;
  }
}
</style>

<style lang="scss">
.pop-line {
  display: flex;
  align-items: center;
  & > div {
    width: 100px;
  }
  & > span {
    flex: 1;
  }
}
</style>

// examples/react/src/App.tsx
import { useState } from 'react'
import { HashRouter, useRoutes, Navigate, Outlet } from 'react-router-dom'
import MenuList from './components/MenuList'
import { Button, Modal, message } from 'antd'
import axios from 'axios'
import { routes } from './router'

// Layout component to match App.vue structure
const Layout = () => {
  const [baseInfo, setBaseInfo] = useState<any>({})

  // Transform routes to match MenuList expectation if needed
  const menuItems = routes.filter(
    item => item.path !== '/' && item.path !== '*'
  )

  const getBaseInfo = () => {
    return axios.get('/getBaseInfo').then(res => {
      setBaseInfo(res.data.data)
      return res.data.data
    })
  }

  const showBaseInfo = () => {
    getBaseInfo().finally(() => {
      if (baseInfo) {
        const displayInfo = Object.keys(baseInfo).reduce((pre, key) => {
          const value = JSON.stringify(baseInfo[key])
          pre += `<div className='pop-line'><div>${key}: </div><span>${value}</span></div>`
          return pre
        }, '')

        Modal.info({
          title: '核心基础信息',
          content: <div dangerouslySetInnerHTML={{ __html: displayInfo }} />,
          width: 600,
          okText: '确定',
          closable: true,
          maskClosable: true
        })
      }
    })
  }

  const cleanTracingList = () => {
    axios.post('/cleanTracingList').then(() => {
      message.success({
        content: '清除成功',
        duration: 1
      })
      // @ts-ignore
      if (window.getAllTracingList) {
        // @ts-ignore
        window.getAllTracingList()
      }
    })
  }

  return (
    <div id="app" style={{ display: 'flex' }}>
      <div className="left-menu">
        <MenuList items={menuItems} />
      </div>
      <div className="right-body">
        <Outlet />
      </div>
      <Button className="clean-1" type="primary" onClick={showBaseInfo}>
        查看核心基础信息
      </Button>
      <div>
        <Button className="clean-2" type="primary" danger onClick={cleanTracingList}>
          清除所有事件信息
        </Button>
      </div>
    </div>
  )
}

// Router component to handle route definitions
const AppRouter = () => {
  const element = useRoutes([
    {
      path: '/',
      element: <Layout />,
      children: [
        ...routes.map(route => {
          if (route.redirect) {
            return {
              path: route.path,
              element: <Navigate to={route.redirect} replace />
            }
          }
          return {
            path: route.path,
            element: route.element
          }
        })
      ]
    }
  ])
  return element
}

function App() {
  return (
    <HashRouter>
      <AppRouter />
    </HashRouter>
  )
}

export default App
